-- ==============================================================================
-- PATCH: DYNAMIC CATEGORIES
-- ==============================================================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL UNIQUE
);

-- 2. RLS Policies for Categories (Public for Demo)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Public Insert Categories" ON categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Categories" ON categories FOR UPDATE USING (true);
CREATE POLICY "Public Delete Categories" ON categories FOR DELETE USING (true);

-- 3. Seed Default Categories
INSERT INTO categories (name) VALUES 
('Pants'), 
('Shirts'), 
('Dresses'), 
('Accessories'), 
('Shoes'), 
('Other')
ON CONFLICT (name) DO NOTHING;
