-- ==============================================================================
-- PATCH: STORE SETTINGS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL DEFAULT 'Flup POS',
    address TEXT,
    phone TEXT,
    email TEXT,
    tax_rate NUMERIC(4,2) DEFAULT 0.16, -- 16% default
    currency TEXT DEFAULT 'USD'
);

-- Enable RLS
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;

-- Allow public access for now (or restricted to auth users in production)
CREATE POLICY "Public Read Settings" ON store_settings FOR SELECT USING (true);
CREATE POLICY "Public Update Settings" ON store_settings FOR UPDATE USING (true);

-- Check if empty and seed initial row
INSERT INTO store_settings (id, store_name, address, phone, email)
SELECT 1, 'Flup Store', '123 Main St', '555-0000', 'admin@flup.com'
WHERE NOT EXISTS (SELECT 1 FROM store_settings);
