-- ==============================================================================
-- DATABASE SETUP SCRIPT FOR POS & INVENTORY MANAGER
-- ==============================================================================
-- ⚠️ WARNING: This script builds the schema from scratch. 
-- It contains DROP commands that will delete existing data in these tables.
-- ==============================================================================

-- 1. CLEANUP (Optional - Use carefully)
DROP FUNCTION IF EXISTS complete_sale;
DROP VIEW IF EXISTS view_daily_sales;
DROP VIEW IF EXISTS view_low_stock;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS variants;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

-- 2. TABLES

-- Customers Table
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    notes TEXT
);

-- Products Table (Catalog)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    image_url TEXT,
    embedding vector(768) -- Support for future AI Vector Search
);

-- Variants Table (SKUs / Inventory)
CREATE TABLE variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    sku TEXT UNIQUE NOT NULL,
    size TEXT,
    color TEXT,
    cost_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    price NUMERIC(10,2) NOT NULL DEFAULT 0, -- Sale Price
    current_stock INTEGER NOT NULL DEFAULT 0,
    min_stock_threshold INTEGER NOT NULL DEFAULT 5,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders Table (Headers)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    customer_id BIGINT REFERENCES customers(id),
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL, -- 'card', 'cash', 'transfer'
    status TEXT DEFAULT 'completed'
);

-- Order Items Table (Details)
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES variants(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) GENERATED ALWAYS AS (quantity * unit_price) STORED
);

-- 3. VIEWS (For Dashboard & Analysis)

-- View for Low Stock Alerts
CREATE VIEW view_low_stock AS
SELECT 
    p.name as product_name,
    v.sku,
    v.size,
    v.color,
    v.current_stock,
    v.min_stock_threshold,
    p.image_url
FROM variants v
JOIN products p ON v.product_id = p.id
WHERE v.current_stock <= v.min_stock_threshold;

-- View for Daily Sales Chart
CREATE VIEW view_daily_sales AS
SELECT 
    DATE_TRUNC('day', created_at) as day,
    COUNT(id) as total_orders,
    SUM(total_amount) as total_revenue
FROM orders
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY day DESC;

-- 4. FUNCTIONS (RPC)

-- Transactional Sale Completion
-- This function handles the checkout process: deducting stock and recording the order properly.
CREATE OR REPLACE FUNCTION complete_sale(
    p_customer_id BIGINT,
    p_payment_method TEXT,
    p_items JSONB -- Array of objects: { "variant_id": 1, "quantity": 2, "price": 10.00 }
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id BIGINT;
    v_total NUMERIC(10,2) := 0;
    v_item JSONB;
    v_variant_id BIGINT;
    v_qty INTEGER;
    v_price NUMERIC(10,2);
BEGIN
    -- Calculate total
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_qty := (v_item->>'quantity')::INTEGER;
        v_price := (v_item->>'price')::NUMERIC;
        v_total := v_total + (v_qty * v_price);
    END LOOP;

    -- Create Order Header
    INSERT INTO orders (customer_id, payment_method, total_amount, status)
    VALUES (p_customer_id, p_payment_method, v_total, 'completed')
    RETURNING id INTO v_order_id;

    -- Process Items
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_variant_id := (v_item->>'variant_id')::BIGINT;
        v_qty := (v_item->>'quantity')::INTEGER;
        v_price := (v_item->>'price')::NUMERIC;

        -- Deduct Stock
        UPDATE variants
        SET current_stock = current_stock - v_qty,
            updated_at = NOW()
        WHERE id = v_variant_id;

        -- Record Item
        INSERT INTO order_items (order_id, variant_id, quantity, unit_price)
        VALUES (v_order_id, v_variant_id, v_qty, v_price);
    END LOOP;

    RETURN v_order_id;
END;
$$;

-- 5. SEED DATA (Demo Content)

-- Enable RLS (Optional but recommended)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- For this demo, we'll allow public access policies for simplicity
CREATE POLICY "Public Read" ON products FOR SELECT USING (true);
CREATE POLICY "Public Read" ON variants FOR SELECT USING (true);
CREATE POLICY "Public Read" ON orders FOR SELECT USING (true);
-- Note: In production you'd want restrictive policies particularly for writes.

-- Seed Customers
INSERT INTO customers (full_name, email, phone) VALUES 
('Cliente General', 'general@store.com', '555-0000'),
('Juan Perez', 'juan@vip.com', '555-0123');

-- Seed Products & Variants
-- Product 1: Jeans
WITH p AS (
    INSERT INTO products (name, category, description, image_url) 
    VALUES ('Jeans Slim Fit', 'Pants', 'Jeans de mezclilla ajustados', 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=500&q=80') 
    RETURNING id
)
INSERT INTO variants (product_id, sku, size, color, price, current_stock, min_stock_threshold)
SELECT id, 'JNS-BLUE-32', '32', 'Blue', 45.00, 20, 5 FROM p;

-- Product 2: Summer Dress
WITH p AS (
    INSERT INTO products (name, category, description, image_url) 
    VALUES ('Vestido Floral Verano', 'Dresses', 'Vestido ligero para playa', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&q=80') 
    RETURNING id
)
INSERT INTO variants (product_id, sku, size, color, price, current_stock, min_stock_threshold)
SELECT id, 'DRS-FLO-M', 'M', 'Floral', 35.50, 8, 3 FROM p;

-- Product 3: Basic T-Shirt
WITH p AS (
    INSERT INTO products (name, category, description, image_url) 
    VALUES ('Camiseta Básica', 'Shirts', 'Algodón 100% premium', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80') 
    RETURNING id
)
INSERT INTO variants (product_id, sku, size, color, price, current_stock, min_stock_threshold)
SELECT id, 'TSH-WHT-L', 'L', 'White', 15.00, 50, 10 FROM p;

-- Product 4: Leather Belt (Accessory)
WITH p AS (
    INSERT INTO products (name, category, description, image_url) 
    VALUES ('Cinturón de Cuero', 'Accessories', 'Cuero genuino', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80') 
    RETURNING id
)
INSERT INTO variants (product_id, sku, size, color, price, current_stock, min_stock_threshold)
SELECT id, 'BLT-BRN-OS', 'OS', 'Brown', 25.00, 12, 4 FROM p;

-- Seed Sales (History)
-- We'll manually insert a completed order to show data in charts
WITH o AS (
    INSERT INTO orders (customer_id, total_amount, payment_method, created_at)
    VALUES (1, 60.00, 'cash', NOW() - INTERVAL '1 day') -- Yesterday
    RETURNING id
)
INSERT INTO order_items (order_id, variant_id, quantity, unit_price)
SELECT id, (SELECT id FROM variants WHERE sku = 'JNS-BLUE-32' LIMIT 1), 1, 45.00 FROM o;

